import type { ComfyUiSettings } from '@/lib/comfyui-settings';
import type { SharedToolSettings } from '@/lib/settings-cache';
import { validateWorkflowJson, type CustomWorkflowToken } from '@/lib/comfyui-config';
import { fetchWorkflowPreview } from '@/lib/comfyui-requeue';
import type { ComfyUiSettingsSectionId } from '@/lib/settings-comfyui-nav';
import type { HealthResponse } from '@/components/settings/tabs/settings-tool-shared';

export type SettingsComfyConnectionPanelProps = {
  slimSettings?: boolean;
  showAdvanced: boolean;
  sharedSettings: SharedToolSettings;
  sharedMounted: boolean;
  updateSharedSettings: (patch: Partial<SharedToolSettings>) => void;
  mounted: boolean;
  settings: ComfyUiSettings;
  updateSettings: (patch: Partial<ComfyUiSettings>) => void;
  workflowError: string | null;
  setWorkflowError: (value: string | null) => void;
  workflowValidation: ReturnType<typeof validateWorkflowJson> | null;
  previewPrompt: string;
  setPreviewPrompt: (value: string) => void;
  previewLoading: boolean;
  previewError: string | null;
  workflowPreview: Awaited<ReturnType<typeof fetchWorkflowPreview>> | null;
  handlePreviewWorkflow: () => void | Promise<void>;
  handleImportWorkflow: (file: File) => void | Promise<void>;
  notificationPermission: NotificationPermission | 'unsupported';
  handleEnableNotifications: () => void | Promise<void>;
  handleSaveComfySettings: () => void;
  handleResetComfySettings: () => void;
  refreshHealth: () => void | Promise<void>;
  health: HealthResponse | null;
  healBusy?: boolean;
  healProgress?: string | null;
  handleHealAndReady?: () => void | Promise<void>;
  workflowHealthRefresh: number;
  setWorkflowHealthRefresh: (value: number | ((previous: number) => number)) => void;
  setStatus: (status: string | null) => void;
  updateQueueParam: (key: 'seed' | 'width' | 'height' | 'cfg' | 'steps', value: string) => void;
  updateCustomToken: (index: number, patch: Partial<CustomWorkflowToken>) => void;
  addCustomToken: () => void;
  removeCustomToken: (index: number) => void;
  handleComfyUiSectionJump: (section: ComfyUiSettingsSectionId) => void;
};
