'use client';

import type { GalleryPanelBodyProps } from '@/components/gallery/gallery-panel-body-types';
import { assembleGalleryPanelBodyProps } from '@/lib/build-gallery-panel-body-props';
import type { GalleryPanelOrchestrationCore } from '@/hooks/gallery-panel/useGalleryPanelOrchestrationCore';

export type UseGalleryPanelOrchestrationResult = {
  showSkeleton: boolean;
  skeletonProps: { showFilters: boolean; compact: boolean };
  bodyProps: GalleryPanelBodyProps | null;
};

export function useGalleryPanelOrchestrationPart2(
  ctx: GalleryPanelOrchestrationCore
): UseGalleryPanelOrchestrationResult {
  const {
    showHeader,
    showFilters,
    compact,
    limit,
    leanGallery,
    leanBulkEnabled,
    bulkEnabled,
    paginationEnabled,
    pickFor,
    entries,
    filter,
    setFilter,
    tools,
    models,
    userTags,
    customGroups,
    renameCustomGroup,
    deleteCustomGroup,
    removeEntries,
    toggleFavorite,
    setFavorites,
    setReviewRatings,
    setReviewRating,
    refreshPending,
    clearAll,
    activeJobs,
    galleryCapWarning,
    galleryStats,
    heldMaxCount,
    activeProjectId,
    projects,
    browse,
    displayPlan,
    lightboxState,
    ui,
    selection,
    compareHandlers,
    resetCompare,
    review,
    onDownloadImage,
    lightboxSlideChrome,
    bulkExperimentHandlers,
    experimentGridHandlers,
    renderGalleryCard,
    retryFailedEntries,
    exportCapKeepers,
    showSkeleton,
    embeddingSearchActive,
    similarSearchActive,
    embeddingSearchLoading,
    similarSearchLoading,
    embeddingSearchUnavailable,
  } = ctx;

  const bodyProps: GalleryPanelBodyProps | null = showSkeleton
    ? null
    : assembleGalleryPanelBodyProps({
        chrome: {
          showHeader,
          showFilters,
          compact,
          limit,
          leanGallery,
          leanBulkEnabled,
          bulkEnabled,
          paginationEnabled,
          pickFor,
        },
        upload: {
          uploadInputRef: ui.uploadInputRef,
          importDroppedImages: ui.importDroppedImages,
        },
        lightbox: {
          resolvedLightbox: lightboxState.resolvedLightbox,
          closeLightbox: lightboxState.closeLightbox,
          onIndexChange: index =>
            lightboxState.setLightbox(previous =>
              previous
                ? {
                    ...previous,
                    index,
                    title: lightboxState.lightboxPlaylist.titles[index] ?? previous.title,
                  }
                : previous
            ),
          onDownloadImage,
          slideChrome: lightboxSlideChrome,
          slideshowPlaying: lightboxState.slideshowPlaying,
          slideshowIntervalMs: lightboxState.slideshowIntervalMs,
          slideshowTransition: lightboxState.slideshowTransition,
          slideshowFullscreen: lightboxState.slideshowFullscreen,
          setSlideshowPlaying: lightboxState.setSlideshowPlaying,
          setSlideshowIntervalMs: lightboxState.setSlideshowIntervalMs,
          setSlideshowTransition: lightboxState.setSlideshowTransition,
          setSlideshowFullscreen: lightboxState.setSlideshowFullscreen,
          playlistLength: lightboxState.lightboxPlaylist.images.length,
        },
        header: {
          activeJobs,
          entriesLength: entries.length,
          uploadingImages: ui.uploadingImages,
          onRefreshPending: () => void refreshPending(),
          onClearAll: clearAll,
        },
        requeueStatus: ui.requeueStatus,
        cap: {
          galleryCapWarning,
          capWizardOpen: ui.capWizardOpen,
          setCapWizardOpen: ui.setCapWizardOpen,
          capEvictionPreview: displayPlan.capEvictionPreview,
          exportCapKeepers,
        },
        auxiliary: {
          duplicateClusters: displayPlan.duplicateClusters,
          duplicateEntriesById: displayPlan.duplicateEntriesById ?? undefined,
          showVisionInbox: displayPlan.showVisionInbox,
          visionInboxQueue: displayPlan.visionInboxQueue,
          setReviewRating,
          setVisionInboxSkipIds: ui.setVisionInboxSkipIds,
          setVisionInboxOpen: ui.setVisionInboxOpen,
        },
        browse: {
          filter,
          setFilter,
          entries,
          visibleEntries: displayPlan.visibleEntries,
          galleryStats,
          heldMaxCount,
          activeProjectId,
          projectFilterId: browse.projectFilterId,
          setProjectFilterId: browse.setProjectFilterId,
          refreshPending,
          tools,
          models,
          userTags,
          customGroups,
          renameCustomGroup,
          deleteCustomGroup,
          projects,
          sort: browse.sort,
          setSort: browse.setSort,
          pageSize: browse.pageSize,
          setPageSize: browse.setPageSize,
          embeddingSearchActive,
          embeddingSearchLoading,
          similarSearchLoading,
          embeddingSearchUnavailable,
          layout: browse.layout,
          setLayout: browse.setLayout,
          density: browse.density,
          setDensity: browse.setDensity,
          totalFiltered: displayPlan.totalFiltered,
          currentPage: displayPlan.currentPage,
          totalPages: displayPlan.totalPages,
          showPagination: displayPlan.showPagination,
          startSlideshow: lightboxState.startSlideshow,
          startFullscreenSlideshow: lightboxState.startFullscreenSlideshow,
          retryFailedEntries,
          setPage: browse.setPage,
          effectivePageSize: displayPlan.effectivePageSize,
          clearGalleryFilters: browse.clearGalleryFilters,
        },
        selection: {
          selectedEntries: selection.selectedEntries,
          selectedIds: selection.selectedIds,
          selectAllVisible: selection.selectAllVisible,
          clearSelection: selection.clearSelection,
          openCompare: ui.openCompare,
          setSelectedIds: selection.setSelectedIds,
          setCompareOpen: ui.setCompareOpen,
        },
        bulk: {
          paramAxis: ui.paramAxis,
          setParamAxis: ui.setParamAxis,
          similarSearchActive,
          bulkExperimentHandlers,
          downloadError: ui.downloadError,
          setLoraExportScope: ui.setLoraExportScope,
          setLoraExportOpen: ui.setLoraExportOpen,
        },
        modals: {
          compareOpen: ui.compareOpen,
          compareHandlers,
          resetCompare,
          openEntryLightbox: lightboxState.openEntryLightbox,
          workflowEntry: ui.workflowEntry,
          setWorkflowEntry: ui.setWorkflowEntry,
          loraExportOpen: ui.loraExportOpen,
          loraExportScope: ui.loraExportScope,
        },
        grid: {
          lineageGroups: displayPlan.lineageGroups,
          collapsedLineageGroups: ui.collapsedLineageGroups,
          toggleLineageGroup: ui.toggleLineageGroup,
          experimentGroups: displayPlan.experimentGroups,
          collapsedExperimentGroups: ui.collapsedExperimentGroups,
          toggleExperimentGroup: ui.toggleExperimentGroup,
          experimentWinners: browse.experimentWinners,
          experimentGridHandlers,
          galleryCardGridClass: displayPlan.galleryCardGridClass,
          galleryVirtualGridClass: displayPlan.galleryVirtualGridClass,
          renderGalleryCard,
        },
        review: {
          reviewFocusEntry: review.reviewFocusEntry,
          reviewFocusIndex: review.reviewFocusIndex,
          handleReviewRating: review.handleReviewRating,
          toggleFavorite,
        },
        removeEntries,
        setFavorites,
        setRequeueStatus: ui.setRequeueStatus,
      });

  return {
    showSkeleton,
    skeletonProps: { showFilters, compact },
    bodyProps,
  };
}
